### ISSUE TITLE
View hierarchy debugger

### ISSUE THREAD

**Issue by richardtop** [phillfarrugia/shortcuts-drawer-view#1]
Hi Phil,
great work!
What view hierarchy debugger do you use in this screenshot?
Were you able to inspect a third-party app with it?
![image](https://user-images.githubusercontent.com/8013017/47247616-7bb62c80-d40d-11e8-8759-970a7ff6bcfa.png)

**Comment by phillfarrugia** [comment]
@richardtop I'm using Reveal (https://revealapp.com/). It can indeed be used to inspect third party applications (http://petersteinberger.com/blog/2013/how-to-inspect-the-view-hierarchy-of-3rd-party-apps/) but takes some tinkering.
